name: Daily Tasks5

on:
  schedule:
    # Runs at 10:30 am UTC+8 every day
    - cron: "20 5 * * *"
  workflow_dispatch:

jobs:
  run-tasks:
    name: Run FF14 Risingstone Tasks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: docker://ghcr.io/starhearthunt/ff14risingstone_sign_task:master
        with:
          cookie: ${{ secrets.COOKIE5 }}
          user_agent: ${{ secrets.USER_AGENT }}
